#!/bin/sh
# 
# Updates the existing database by 
# restoring from the mysqldump file in the commit that just happened
# 
# You may need to chmod +x .git/hooks/mysql_config

. .git/hooks/mysql_config

$path_to_binary"/mysql" --user=$mysql_user --password=$mysql_pass $dbname  < $rootdir/$path_to_file/$dbname.sql

echo "Restored database from $dbname.sql to MySql"